---
# tasks file for docker-ce

- name: ensure docker dependencies are installed
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']
    state: present
  tags: [ 'packages', 'docker' ]

- name: add docker’s official gpg key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    id: 0EBFCD88
    state: present

- name: add docker stable repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable'
    filename: docker
    state: present
    update_cache: yes

- name: install docker
  package:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: present

- name: remove upstart config file
  file:
    path: /etc/default/docker
    state: absent

- name: ensure systemd directory exists
  file:
    path: /etc/systemd/system
    state: directory
    mode: 0755

- name: generate systemd unit file
  template:
    src: docker.service.j2
    dest: /etc/systemd/system/docker.service
    mode: 0644
  register: docker_register_systemd_service

- name: reload systemd daemon
  systemd: daemon_reload=yes
  notify:
    - restart docker
  when: (docker_register_systemd_service|d() and docker_register_systemd_service is changed)

- name: add the ansible user to the docker group
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes

- name: install docker compose
  get_url:
    url: 'https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64'
    dest: '/usr/local/bin/docker-compose'
    force: yes
    mode: 0755
